server:
  port: 9797

spring:
  datasource:
    url: jdbc:mysql://121.14.12.105:3306/wds?useUnicode=true&allowMultiQueries=true
    username: root
    password: sinocom11
  redis:
    port: 6379
    password: 123456
    host: 127.0.0.1

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

ignore:
  path: /user/login